version: "3.7"

services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234qweR
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - backend

  elas-backend:
    image: elas-backend
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    restart: unless-stopped
    environment:
      - FLASK_APP=application
      - FLASK_ENV=development
      - POSTGRES_USER=postgres
      - POSTGRES_HOST=db
      - POSTGRES_DB=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_PASS=1234qweR
      - JWT_SECRET_KEY=secret
    ports:
      - "5000:5000"
    volumes:
      - ./backend/:/app/
    depends_on:
      - db
    networks:
      - backend
      - frontend

  elas-frontend:
    image: elas-frontend
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    restart: unless-stopped
    stdin_open: true
    environment:
      - REACT_APP_BASE_URL=http://localhost:5000
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - elas-backend
    networks:
      - frontend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  db:
    driver: local
